# -------------------------
# Dongle USB -> hôte
# -------------------------

CONFIG_ZMK_USB=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
CONFIG_USB_DEVICE_PRODUCT="dullboy dongle"

# -------------------------
# Architecture dongle ZMK
# -------------------------

CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# -------------------------
# BLE
# -------------------------

CONFIG_ZMK_BLE=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_SETTINGS=y

# -------------------------
# Liaison BLE
# -------------------------

CONFIG_BT_CTLR_PHY_2M=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=30
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

CONFIG_BT_AUTO_PHY_UPDATE=y
CONFIG_BT_GATT_AUTO_SEC_REQ=y

# -------------------------
# Reconnexion automatique
# -------------------------

CONFIG_BT_BACKGROUND_SCAN_INTERVAL=2048
CONFIG_BT_BACKGROUND_SCAN_WINDOW=18

# -------------------------
# Robustesse pile Bluetooth
# -------------------------

CONFIG_BT_CONN_TX_MAX=5
CONFIG_BT_CONN_RX_MAX=5
CONFIG_BT_WORK_QUEUE_STACK_SIZE=2048

# -------------------------
# Modules inutiles
# -------------------------

CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_BACKLIGHT=n
CONFIG_ZMK_DISPLAY=n

# -------------------------
# Gestion des bonds
# -------------------------

CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
