# -------------------------
# USB vers l'hôte
# -------------------------

CONFIG_ZMK_USB=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="dullboy dongle"
CONFIG_ZMK_USB_INIT_PRIORITY=90

# -------------------------
# Architecture dongle ZMK
# -------------------------

CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# -------------------------
# BLE central uniquement
# -------------------------

CONFIG_ZMK_BLE=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_PERIPHERAL=n

CONFIG_BT_SETTINGS=y

CONFIG_BT_MAX_CONN=1
CONFIG_BT_MAX_PAIRED=1
CONFIG_ZMK_BLE_PROFILE_COUNT=1

# -------------------------
# Optimisation BLE
# -------------------------

CONFIG_BT_CTLR_PHY_2M=y
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251

CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=30
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

CONFIG_BT_AUTO_PHY_UPDATE=y
CONFIG_BT_GATT_AUTO_SEC_REQ=y

# -------------------------
# Reconnexion rapide
# -------------------------

CONFIG_BT_BACKGROUND_SCAN_INTERVAL=2048
CONFIG_BT_BACKGROUND_SCAN_WINDOW=18

# -------------------------
# Optimisation HID
# -------------------------

CONFIG_ZMK_HID_REPORT_QUEUE_SIZE=20

# -------------------------
# Suppression modules inutiles
# -------------------------

CONFIG_KSCAN=n
CONFIG_ZMK_KEYMAP=n
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_BACKLIGHT=n
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_WIDGETS=n

# -------------------------
# Optimisation mémoire BLE
# -------------------------

CONFIG_BT_RX_BUF_COUNT=3
CONFIG_BT_L2CAP_TX_BUF_COUNT=3
