CONFIG_ZMK_USB=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="dullboy dongle"

CONFIG_ZMK_BLE=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_PERIPHERAL=n

CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

CONFIG_BT_SETTINGS=y

CONFIG_BT_MAX_CONN=1
CONFIG_BT_MAX_PAIRED=1
CONFIG_ZMK_BLE_PROFILE_COUNT=1

CONFIG_KSCAN=n
CONFIG_ZMK_KEYMAP=n

CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=30
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

CONFIG_BT_AUTO_PHY_UPDATE=y
CONFIG_BT_GATT_AUTO_SEC_REQ=y
